version: '3.8'

services:
  auth-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=auth
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=24h
      - REFRESH_EXPIRATION=720h
      - GIN_MODE=release
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      - FROM_NAME=${FROM_NAME}
      - VERIFY_CODE_EXPIRATION=15m
      - APP_URL=${APP_URL}
      - TZ=Europe/Paris
    depends_on:
      - mongodb
    networks:
      - auth-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  mongodb:
    image: mongo:6.0
    container_name: auth-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - auth-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  auth-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local